spring.application.name=productService

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_product_service
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update